WebNanotech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('sesiones/', include('sesiones.urls')),
    path('', include('gestion.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




carro/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from  . import views



urlpatterns = [
    path('',views.carrito, name='carro'),
    path('agregar/<str:pk>', views.agregar_producto, name="agregar"),

    path('eliminar/<str:pk>', views.eliminar_producto, name="eliminar"),

    path('restar/<str:pk>', views.restar_producto, name="restar"),

    path('sumar/<str:pk>', views.sumar_producto, name="sumar"),

    path('limpiar/', views.limpiar_carroproducto, name="limpiar"),
    
    ]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedidos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from  . import views

app_name= "pedidos"

urlpatterns = [
   
    path('pedido/', views.mandar_pedido, name="mandar"),
    

    ]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/models.py
from django.db import models

# Create your models here.




carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from gestion.models import Producto
from django.contrib.auth.decorators import login_required
# Create your views here.

def carrito(request):
    context={"carro":carrito}
    return render(request, "carro.html",context)

@login_required(login_url='login')
def agregar_producto(request, pk):
    # if request.method == 'POST':
    #     carro = Carro(request)
    #     cantidad_producto = request.POST.get('cantidad_p')
        
    #     producto = Producto.objects.get(sku=pk)

    #     carro.agregar(producto,cantidad_producto)
    
    #     return redirect("index")
    if request.method == 'POST':
        carro = Carro(request)
        cantidad_producto = int(request.POST.get('cantidad_p', 1))  # Establece una cantidad predeterminada de 1 si no se envía cantidad
        
        producto = Producto.objects.get(sku=pk)
        
        # Comprueba si el producto ya está en el carrito
        if carro.existe(producto):
            # Actualiza la cantidad del producto en el carrito
            carro.actualizar(producto, cantidad_producto)
        else:
            # Agrega el producto al carrito si no existe
            carro.agregar(producto, cantidad_producto)
    
        return redirect("index")

@login_required(login_url='login')
def eliminar_producto(request,pk):
    carro= Carro(request)
    producto= Producto.objects.get(sku=pk)

    carro.eliminar(producto)
    
    return redirect("carro")

@login_required(login_url='login')
def sumar_producto(request,pk):
    carro= Carro(request)
    producto= Producto.objects.get(sku=pk)

    carro.sumar_producto(producto=producto)
    
    return redirect("carro")

@login_required(login_url='login')
def restar_producto(request,pk):
    carro= Carro(request)
    producto= Producto.objects.get(sku=pk)

    carro.restar_producto(producto=producto)
    
    return redirect("carro")

@login_required(login_url='login')
def limpiar_carroproducto(request):
    carro= Carro(request)
    carro.limpiar_carro()
    
    return redirect("carro")


carro/templates/carro.html
{% extends "base.html" %}

    {% block tittle %} Carrito de compra {% endblock %}


    {% block content %}

    <div>
            
        <h1 class="text-center">Mi carrito</h1> <br>
        
        <table class="table table-hover table-bordered">
            <tr>
                <th>SKU</th>
                <th>Foto</th>                
                <th>Nombre</th>                
                <th>Marca</th>
                <th>Cantidad</th>
                <th>Precio unitario</th>
                <th>subtotal</th>
                <th>Sumar/Restar</th>
                <th>Eliminar</th>
                
            </tr>
            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}
            <tr>
                <td>{{value.sku}} </td>
                <td><img src="{{value.foto|slice:'1:'}}" alt="{{ value.nombre }}" width="100" height="100"> </td>
                <td>{{value.nombre}} </td>
                <td>{{value.marca}} </td>
                <td>{{value.cantidad}} </td>
                <td>{{value.precio}} </td>
                <td>{{value.subtotal}}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'sumar' pk=value.sku %}">+</a>
                    <a class="btn btn-primary" href="{% url 'restar' pk=value.sku %}">-</a>
                </td>
                <td><a href="{% url 'eliminar' pk=value.sku %}">Quitar articulos</a></td>
                
            </tr>
            {% endfor %}
            <p>Precio final: {{importe_total_carro}}</p>

            {%elif user.is_authenticated%}
            
            <div class="alert alert-warning" role="alert">
                No has agregado articulos a tu carrito :p
            </div>
            {% else %}
            <div class="alert alert-warning" role="alert">
                Inicia sesion antes de agregar 
            </div>
            {% endif %}
        </table>            
        <div>
            {% if user.is_superuser %}
            <a class="btn btn-primary" href="{% url 'pedidos:mandar'%}">Pagar</a>
            <br>
            <a href="{% url 'index'%}">Volver tienda</a>
            {% else %}
            <a href="{% url 'index'%}">Volver tienda</a>
            {% endif %}
            

        </div>
    </div>
    {%endblock%}